from __future__ import annotations
from datetime import datetime, timezone
from pathlib import Path

import click

from mind.config import Config
from mind.evolve import run_evolve
from mind.hook import install_hook
from mind.index import Index, SourceIndex
from mind.sync import run_sync


_MIND_MD_TEMPLATE = """\
# mind — {project_name}
_synced: {date} | sessions: 0 | tools: {llm}_

## behavior
Rules extracted from user corrections. Never compressed. Highest priority.

## context
Project just initialized. No session history yet.

## active
(none yet)

## decisions
(none yet)

## lessons
(none yet)

## history
{date}: mind initialized.
"""

_README_MD_TEMPLATE = """\
# _mind

AI context memory for **{project_name}**.

- [`mind.md`](mind.md) — source of truth: rules, decisions, lessons, active work.
- [`index.yaml`](index.yaml) — sync state (auto-managed, do not hand-edit).

## Usage

```bash
mind sync     # extract new AI transcripts and update mind.md (incremental)
mind rebuild  # delete _mind/ entirely and recompile from all transcripts
mind status   # show sync state and tracked tools
```

> Generated by [mind](https://github.com/SauliusDev/mind) on {date}.
"""

_TOML_TEMPLATE = """\
[project]
name = "{project_name}"

[llm]
provider = "{llm}"
# haiku_command = "claude -p {{prompt}} --model claude-haiku-4-5-20251001"

[tools]
enabled = ["claude", "gemini", "cursor", "codex", "copilot"]

[limits]
chunk_size = 30
max_message_chars = 500
mind_max_lines = 150
"""


@click.group()
def main() -> None:
    """mind — persistent AI context management."""


@main.command()
@click.option("--project-path", default=".", show_default=True)
@click.option("--name", prompt="Project name")
@click.option("--llm", default="claude", show_default=True, help="LLM provider: claude|gemini|codex")
def init(project_path: str, name: str, llm: str) -> None:
    """Initialize mind in a project."""
    root = Path(project_path).resolve()
    mind_dir = root / "_mind"
    mind_dir.mkdir(parents=True, exist_ok=True)

    today = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")

    mind_md = mind_dir / "mind.md"
    if not mind_md.exists():
        mind_md.write_text(_MIND_MD_TEMPLATE.format(project_name=name, date=today, llm=llm))

    readme = mind_dir / "README.md"
    if not readme.exists():
        readme.write_text(_README_MD_TEMPLATE.format(project_name=name, date=today))

    index = Index(
        project=name,
        project_path=str(root),
        last_sync=datetime.now(tz=timezone.utc).isoformat(),
        sync_count=0,
        llm=llm,
        sources={},
    )
    index.write(mind_dir)

    toml_path = mind_dir / "mind.toml"
    if not toml_path.exists():
        toml_path.write_text(_TOML_TEMPLATE.format(project_name=name, llm=llm))

    install_hook(root)
    click.echo(f"✓ mind initialized in {root}")
    click.echo("  _mind/mind.md     created")
    click.echo("  _mind/README.md   created")
    click.echo("  _mind/index.yaml  created")
    click.echo("  _mind/mind.toml   created")
    click.echo("  .git/hooks/post-commit  installed")


@main.command()
@click.option("--project-path", default=".", show_default=True)
def sync(project_path: str) -> None:
    """Extract new transcripts and update mind.md."""
    root = Path(project_path).resolve()
    cfg = Config.load(root)
    mind_dir = root / "_mind"
    run_sync(cfg, mind_dir, str(root))


@main.command()
@click.option("--project-path", default=".", show_default=True)
@click.option("--yes", "-y", is_flag=True, default=False, help="Skip confirmation prompt.")
def rebuild(project_path: str, yes: bool) -> None:
    """Hard reset: delete _mind/ entirely and recompile from all transcripts."""
    root = Path(project_path).resolve()
    mind_dir = root / "_mind"

    if not yes:
        click.echo("⚠  This will DELETE the entire _mind/ folder and rebuild from scratch.")
        click.echo(f"   Path: {mind_dir}")
        if not click.confirm("Continue?", default=False):
            click.echo("Aborted.")
            return

    cfg = Config.load(root)

    if mind_dir.exists():
        import shutil
        shutil.rmtree(mind_dir)
        click.echo(f"✓ deleted {mind_dir}")

    mind_dir.mkdir(parents=True)
    today = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")

    (mind_dir / "mind.md").write_text(
        _MIND_MD_TEMPLATE.format(project_name=cfg.project_name, date=today, llm=cfg.llm_provider)
    )
    (mind_dir / "README.md").write_text(
        _README_MD_TEMPLATE.format(project_name=cfg.project_name, date=today)
    )
    Index(
        project=cfg.project_name,
        project_path=str(root),
        last_sync="2000-01-01T00:00:00+00:00",
        sync_count=0,
        llm=cfg.llm_provider,
        sources={},
    ).write(mind_dir)

    click.echo("✓ _mind/ rebuilt — running full sync from all transcripts...")
    run_sync(cfg, mind_dir, str(root))


@main.command()
@click.option("--project-path", default=".", show_default=True)
def status(project_path: str) -> None:
    """Show sync status and tracked tools."""
    root = Path(project_path).resolve()
    try:
        cfg = Config.load(root)
    except FileNotFoundError:
        click.echo("✗ _mind/mind.toml not found. Run: mind init")
        return

    index = Index.load(root / "_mind")
    click.echo(f"project:    {cfg.project_name}")
    click.echo(f"last sync:  {index.last_sync or 'never'}")
    click.echo(f"sync count: {index.sync_count}")
    click.echo(f"llm:        {cfg.llm_provider}")
    click.echo("tools:")
    for tool in cfg.enabled_tools:
        count = len(index.known_files(tool))
        click.echo(f"  {tool:<10} {count} files tracked")


@main.command()
@click.option("--project-path", default=".", show_default=True)
@click.option(
    "--write",
    is_flag=True,
    default=False,
    help="Write suggested rules/skills/CLAUDE.md to .claude/ directory.",
)
def evolve(project_path: str, write: bool) -> None:
    """Analyse full session history and suggest .claude/ artifacts."""
    root = Path(project_path).resolve()
    cfg = Config.load(root)
    mind_dir = root / "_mind"
    if not mind_dir.exists():
        click.echo("✗ _mind/ not found. Run: mind init")
        return
    run_evolve(cfg, root, mind_dir, write=write)
